### ISSUE TITLE
Update to version 3.0.1 of chevrotain

### ISSUE THREAD

**Issue by Ellen102** [scratch4d/scratch-LN#15]
+ cleaner notation of ifs.
https://github.com/SAP/chevrotain/blob/master/BREAKING_CHANGES.md#300

**Comment by bd82** [comment]
Use 3.0.1 as 3.0.0 had a slight unplanned regression.
https://github.com/SAP/chevrotain/blob/master/CHANGELOG.md#301-2-23-2018

😄

**Comment by Ellen102** [comment]
Nice! thank you! 😃
