### ISSUE TITLE
support comments

### ISSUE THREAD

**Issue by Ellen102** [scratch4d/scratch-LN#39]
add comments to the language

**Comment by pdawyndt** [comment]
Both Scratch-LN comments (no impact on Scratch blocks, but instrumental for Scratch-LN developers) and Scratch comments should be supported:

- Scratch-LN comments
  - line comments: `// ...`
  - block comments: `/* ... */`
- Scratch comments
  - block comments: `| ... |`

**Comment by Ellen102** [comment]
done, see the example button in the live preview for an example. Although, comments look weird in the read-only version see [test](https://scratch4d.github.io/scratch-LN/example/test.html)
