### ISSUE TITLE
update Scratch 3.0 blocks to latest version

### ISSUE THREAD

**Issue by pdawyndt** [scratch4d/scratch-LN#50]
altough they have no real release numbers up until now (only one release of version 0.1.0), the latest version of Scratch 3.0 blocks has already evolved (support for extensions, translations, ...)

**Comment by Ellen102** [comment]
I updated to a newer version with npm. pen blocks are removed (extensions see #63 ) and  some blocks are removed in sounds (atm still visible in red [the test](https://scratch4d.github.io/scratch-LN/example/test.html) but will be removed soon)

**Comment by pdawyndt** [comment]
@Ellen102 sound blocks also have become an extension in Scratch 3.0, just like the pen blocks
