### ISSUE TITLE
hat and cap blocks should start a new stack

### ISSUE THREAD

**Issue by pdawyndt** [scratch4d/scratch-LN#56]
This is not clear from the grammer, but should be handled by the visitor.

**Comment by Ellen102** [comment]
already works for define blocks in the current version on develop & gh-pages

**Comment by Ellen102** [comment]
To methods are related to this
- `visitor.interruptStack();` Indicates the previous start has ended, should be called before creating a hat block xml, after cap block xml.
- ´visitor.startStack();` before building the new stack, after creation of the hat block xml. This will be called by the stack(ctx) method when the stack was interrupted.
