### ISSUE TITLE
modifiers for comments

### ISSUE THREAD

**Issue by Ellen102** [scratch4d/scratch-LN#66]
allow modifiers for comments with the purpose of:
- In Scratch it is possible to set comments 'minimized'. So shouldn't we allow this in Scratch-LN?
- set location of comments
- set width and height of the comment

**Comment by pdawyndt** [comment]
@Ellen102 seems like a good extension to the grammar; after all, one of the design principles should be that it should be possible to describe every block layout in Scratch using Scratch-LN

**Comment by pdawyndt** [comment]
my attempt to draft some initial Scratch-LN design principles:

- Scratch-LN can be used to describe every block layout in Scratch
- Scratch-LN should reflect the block layout in Scratch as close as possible

**Comment by pdawyndt** [comment]
@Ellen102 would you put the comment modifiers inside 

```
| comments go in between bars ::position(0, 0) |
```

or outside of the bars

```
| comments go in between bars | ::position(0, 0)
```

**Comment by Ellen102** [comment]
Comments should also have an ID.
**practical**
- in the first case, between bars: 
     - logic possibility: 
         - create a token VerticalBar
         - reuse the Label-token -> more escaping necessary e.g. newlines,
         - create a rule comment: VerticalBar-Label-annotations-VerticalBar
    - less logic possibility: define different tokens (I am not sure whether this will work)
        -  Start: matching a vertical bar followed by everything that is not the start of something or a vertical bar |[^|@:(?!:)]+ 
        -  End: matching a single vertical bar
        - rule: Start (or End in case of empty comment)-modifiers-ID-End
- in the second case, outside the bars:: 
    - the annotations rule has to be reconsidered, no flexible order any more. 
    - the id of the block has to be before the comment so that the id after the comment is linked to the comment
    - a rule comment: Comment-modifiers-ID

**examples**
- first case, between bars: 
    - `block ::m | c ::m @id | @id2`
    - `block ::m  @id2 | c ::m @id |`
    - `block { ( r::m  @idr | cr ::m @idcr | )@idi} ::m  @id2 | cb::m @idcb |`
    - `block { ( r::m  | cr ::m @idcr | @idr )@idi} ::m  @id2 | cb::m @idcb |`
- second case, outside the bars:
    - `block text ::blockmodifier @blockid |comment| ::commentmodifier @commentid`
    - `stackblock {(reporterblock ::reporterblockmodifier @reporterblockid |comment for reporterblock| ::reportercommentmodifier @reportercommentid ) @inputid} ::stackblockmodifier @stackblockid |comment for stackblock| ::stackblockcommentmodifier @stackblockcommentid`

**conclusion**
The notation with modifiers and ids between bars is more similar to the notation of reporterblock and booleanblocks. However comments are also something different, so it is for me not necessary that it is similar. Comments can only be at the end of a line. A fixed order might be less confusing. 
I think the second case, outside the bars, will be easier and faster to implement.  I do not see any confusion in the notion about what belongs to what. 
 So at first sight,  I prefer outside the bars.

**Comment by pdawyndt** [comment]
I'm fine with outside the bars.

**Comment by pdawyndt** [comment]
@Ellen102  could you indicate what syntax you have in mind when you want to fix the position of both the repeat block and the comment in the following Scratch-LN statement

```
repeat {10} | comment about repetition block |
```

would it be something like

```
repeat {10} ::position(10, 10) | comment about repetition block | :: position(20, 20)
```

**Comment by Ellen102** [comment]
yes, indeed. see [the documentation of the parser](https://github.com/scratch4d/scratch-LN/blob/develop/documentation_parser/generated_diagrams.png)  modifiers and ids for comments are now allowed by the grammar. ids should be set correctly by the visitor. At the moment there are no modifiers implemented yet for the comments.
