### ISSUE TITLE
some more suggestions about grammer rules

### ISSUE THREAD

**Issue by pdawyndt** [scratch4d/scratch-LN#67]
@Ellen102 here are some suggestions for minor changes in the grammar rules after reviewing the new version that we've made yesterday

- [x] rename rule `delimiter` as `delimiters` to better indicate that it stands for zero or more delimiters, and switch the components `Delimiter` and `StackDelimiter` in that rule to reflect the priority: `StackDelimiter` takes precedence over `Delimiter`
- [x] rename `StackDelimiter` as `MultipleDelimiters` to better indicates that it stands for more than one successive delimiters
- [x] move optional `Delimiter` after the `End` in the `clause` rule to the position before `Else` in the `ifelse` rule (as it was at some point yesterday); this better reflects the fact that a `stack` eats a possible delimiter that follows the `stack`, whereas a `block` should never eat a possible delimiter that follows the `block`; as such, a `clause` at the end of a `composite block` should never eat a possible delimiter that follows it, but when the `clause` is in the middle of a `block` (as in the `ifelse` rule) it should eat a possible delimiter that follows it

**Comment by Ellen102** [comment]
I still have problems with the case
```
if <>
end
else
end
```
It is a minor issue as the following works fine. 
```
if <>
else
end
```
