### ISSUE TITLE
comments should not eat newlines at the end

### ISSUE THREAD

**Issue by pdawyndt** [scratch4d/scratch-LN#79]
this does not work for the moment

```
say "hello" // comments
say "hello" // comments
```

this does not render two blocks !!

**Comment by Ellen102** [comment]
What in this case?
```
b1
//s
b2
```
There is a newline after every line. Is this one stack or two stacks?

**Comment by Ellen102** [comment]
now there are problems in the case:

```
b1

//asdf
//asdf

b2
```

**Comment by Ellen102** [comment]
line and block comments eat an optional leading delimiter followed by optional whitespace. 
The motivation is that this should be 2 consecutive blocks in a single stack.
```
b1
//comment
b2
```

**Comment by Ellen102** [comment]
issues after the last update:
reason: A multiline input gets split into two tokens
```
a 

//x
b
```
similar
```
a;; //b;x
```
```
a 

/*x*/
b
```
```
a b c

/*x*/

```

**Comment by Ellen102** [comment]
Allow an optional delimiter after MultipleDelimiters in the stackDelimiter rule. 
Only one Delimiter should be sufficient. I do not think it is possible to create a text that is tokenized as more Delimiter tokens after each others
