### ISSUE TITLE
if blocks with a condition dont render

### ISSUE THREAD

**Issue by martinohanlon** [scratch4d/scratch-LN#98]
I was experimenting with Scratch-LN and I noticed a problem that if blocks dont render if they contain a condition.

This simple test script:

```
when gf clicked
if <key [left arrow] pressed?>
  move {3} steps
end
```

which results in a blank output.

When changed to:

```
when gf clicked
if <>
  move {3} steps
end
```

I get the expected output.

![image](https://user-images.githubusercontent.com/2329501/46788374-d5459980-cd31-11e8-892c-0d19fada297e.png)

I generated the code using the blocks.html tool - so hopefully the syntax is correct!

**Comment by Ellen102** [comment]
Try using `&lt;` instead of <. 
`<>` does not get recognized as an HTML tag but `<some text>` does, even within `<code>` tags.

Thanks for mentioning it, I should probably add this issue somewhere in my documentation.

**Comment by Ellen102** [comment]
There also might be a browser issue. If the solution above does not fix the problem, let me know which browser and version you are using.

**Comment by martinohanlon** [comment]
Thank you, yes that has resolved the issue.
